### ISSUE TITLE
Missing Signature

### ISSUE THREAD

**Issue by jim256** [briangann/grafana-datatable-panel#146]
I'm now getting this on Grafana 8.0.3:

> Unsigned plugins were found during plugin initialization. Grafana Labs cannot guarantee the integrity of these plugins. We recommend only using signed plugins.
> The following plugins are disabled and not shown in the list below:
> 
>     briangann-datatable-panel
> 
> Missing signature

Could this repo be updated to be signed?

**Comment by briangann** [comment]
taking a look, it may have an older signature than v8 requires.

**Comment by briangann** [comment]
i'm not seeing this with v8.0.3

![image](https://user-images.githubusercontent.com/7364245/122970962-19e3b880-d354-11eb-920b-b08fde217da4.png)

![image](https://user-images.githubusercontent.com/7364245/122970989-236d2080-d354-11eb-9978-f64d64628573.png)

**Comment by jim256** [comment]
Hmm. I'm using Grafana Dockerized. Just removed the image and container and fired it up all fresh with the following in my docker-compose:

```
version: '3.7'

services:

    grafana:
        build:
            context: ./grafana
            args:
                GF_INSTALL_PLUGINS: briangann-datatable-panel
        volumes:
            - grafana:/var/lib/grafana
        container_name: grafana-container
        restart: always
```

Is that not quite the right name of the plugin or something? Am I getting an old version?

The new image gave me Grafana  v8.0.3 (cae5c5e46b) as well.

Got the following from docker-compose as the Grafana container was starting:
```
grafana-container | lvl=info msg="Registering plugin" logger=plugins id=grafana-plugin-admin-app
grafana-container | lvl=warn msg="Some plugin scanning errors were found" logger=plugins errors="plugin 'briangann-datatable-panel' is unsigned"
```

Thoughts?
